# Generated by Django 5.0.4 on 2024-07-16 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=30)),
                ('Prenom', models.CharField(max_length=30)),
                ('Nom_pere', models.CharField(max_length=30)),
                ('Date_naissance', models.DateField()),
                ('Lieu_naissance', models.CharField(max_length=30)),
                ('Telephone', models.CharField(max_length=30)),
                ('Adresse', models.CharField(max_length=30)),
                ('Groupe_sanguin', models.CharField(max_length=30)),
                ('Profession', models.CharField(max_length=30)),
                ('Domaine', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Autre_association', models.BooleanField()),
                ('Application_PDF', models.FileField(upload_to='')),
                ('A_paye', models.BooleanField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Domain', models.CharField(default='', max_length=30)),
                ('Title', models.CharField(max_length=50, unique=True)),
                ('Speciality', models.CharField(default='', max_length=30)),
                ('PDF_sujet', models.FileField(max_length=30, upload_to='')),
                ('Sujet_pris', models.BooleanField(default=False)),
                ('Date_debut', models.DateField()),
                ('Date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=30)),
                ('Prenom', models.CharField(max_length=30)),
                ('Universite', models.CharField(max_length=50)),
                ('promotion', models.CharField(blank=True, max_length=30)),
                ('Annee_etude', models.CharField(max_length=20)),
                ('Annee', models.DateField(default='')),
                ('Telephone', models.CharField(max_length=30)),
                ('PDF_Convention', models.FileField(max_length=20, upload_to='')),
                ('Code', models.CharField(max_length=100)),
                ('Rapport', models.FileField(max_length=30, upload_to='')),
                ('Presentation', models.FileField(max_length=20, unique=True, upload_to='')),
                ('PDF_agreement', models.FileField(default=None, max_length=30, unique=True, upload_to='')),
                ('PDF_Prolongement', models.FileField(upload_to='')),
                ('N_stage', models.IntegerField()),
                ('Email', models.EmailField(default='', max_length=254, unique=True)),
                ('Cerficate', models.FileField(upload_to='')),
                ('PDF_sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.stage')),
            ],
        ),
        migrations.CreateModel(
            name='Superviser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=30)),
                ('Prenom', models.CharField(max_length=30)),
                ('Telephone', models.CharField(max_length=30)),
                ('Profession', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Id_Membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.membre')),
            ],
        ),
        migrations.CreateModel(
            name='super_stage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.stage')),
                ('superviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.superviser')),
            ],
            options={
                'unique_together': {('stage', 'superviser')},
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='Supervisers',
            field=models.ManyToManyField(through='myapi.super_stage', to='myapi.superviser'),
        ),
    ]
