# Generated by Django 5.1.7 on 2025-05-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_history',
            name='Payment_received_PDF_with_signature',
            field=models.FileField(max_length=500, null=True, upload_to='PDF/Payment'),
        ),
    ]
