# Generated by Django 5.0.4 on 2024-07-16 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaire',
            name='PDF_Convention',
        ),
        migrations.RemoveField(
            model_name='stagiaire',
            name='PDF_sujet',
        ),
        migrations.AlterField(
            model_name='membre',
            name='Application_PDF',
            field=models.FileField(upload_to='PDF/Application_PDF'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='PDF_sujet',
            field=models.FileField(upload_to='PDF/Project_Subject_PDF'),
        ),
        migrations.CreateModel(
            name='stage_stagiaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PDF_Convention', models.FileField(upload_to='PDF/Convention')),
                ('PDF_Agreement', models.FileField(upload_to='PDF/Agreement')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.stage')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.stagiaire')),
            ],
            options={
                'unique_together': {('stage', 'stagiaire')},
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='Stagiers',
            field=models.ManyToManyField(through='myapi.stage_stagiaire', to='myapi.stagiaire'),
        ),
    ]
