# Generated by Django 5.0.4 on 2024-07-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_remove_stagiaire_pdf_convention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='Application_PDF',
            field=models.FileField(max_length=500, upload_to='PDF/Application_PDF'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='PDF_sujet',
            field=models.FileField(max_length=500, upload_to='PDF/Project_Subject_PDF'),
        ),
        migrations.AlterField(
            model_name='stage_stagiaire',
            name='PDF_Agreement',
            field=models.FileField(max_length=500, upload_to='PDF/Agreement'),
        ),
        migrations.AlterField(
            model_name='stage_stagiaire',
            name='PDF_Convention',
            field=models.FileField(max_length=500, upload_to='PDF/Convention'),
        ),
    ]
