# Generated by Django 5.0.4 on 2024-07-16 13:31

import django.core.validators
import myapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_membre_application_pdf_alter_stage_pdf_sujet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='Application_PDF',
            field=models.FileField(max_length=500, upload_to='PDF/Application_PDF', validators=[django.core.validators.FileExtensionValidator(['pdf']), myapi.models.validate_file_nimetype]),
        ),
        migrations.AlterField(
            model_name='stage',
            name='PDF_sujet',
            field=models.FileField(max_length=500, upload_to='PDF/Project_Subject_PDF', validators=[django.core.validators.FileExtensionValidator(['pdf']), myapi.models.validate_file_nimetype]),
        ),
        migrations.AlterField(
            model_name='stage_stagiaire',
            name='PDF_Agreement',
            field=models.FileField(max_length=500, upload_to='PDF/Agreement', validators=[django.core.validators.FileExtensionValidator(['pdf']), myapi.models.validate_file_nimetype]),
        ),
        migrations.AlterField(
            model_name='stage_stagiaire',
            name='PDF_Convention',
            field=models.FileField(max_length=500, upload_to='PDF/Convention', validators=[django.core.validators.FileExtensionValidator(['pdf']), myapi.models.validate_file_nimetype]),
        ),
    ]
