# Generated by Django 5.0.4 on 2024-07-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_membre_application_pdf_alter_stage_pdf_sujet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='Application_PDF',
            field=models.FileField(max_length=500, upload_to='PDF/Application_PDF'),
        ),
    ]
