# Generated by Django 5.1.7 on 2025-04-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_payment_history_id_membre'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_history',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
