# Generated by Django 5.0.4 on 2024-07-30 09:00

import django.core.validators
import myapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_membre_application_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaire',
            name='Cerficate',
        ),
        migrations.RemoveField(
            model_name='stagiaire',
            name='PDF_Prolongement',
        ),
        migrations.RemoveField(
            model_name='stagiaire',
            name='PDF_agreement',
        ),
        migrations.AddField(
            model_name='stage_stagiaire',
            name='Cerficate',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='stage_stagiaire',
            name='PDF_Prolongement',
            field=models.FileField(max_length=500, null=True, upload_to='PDF/Prolongment', validators=[django.core.validators.FileExtensionValidator(['pdf']), myapi.models.validate_file_nimetype]),
        ),
        migrations.AddField(
            model_name='stage_stagiaire',
            name='prolongment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membre',
            name='Application_PDF',
            field=models.FileField(max_length=500, upload_to='PDF/Application_PDF', validators=[django.core.validators.FileExtensionValidator(['pdf']), myapi.models.validate_file_nimetype]),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='Presentation',
            field=models.FileField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='Rapport',
            field=models.FileField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='Telephone',
            field=models.CharField(max_length=50),
        ),
    ]
