# Generated by Django 5.0.4 on 2024-07-30 09:10

import django.core.validators
import myapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_remove_stagiaire_cerficate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='A_paye',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='membre',
            name='Adresse',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membre',
            name='Domaine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membre',
            name='Lieu_naissance',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membre',
            name='Nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membre',
            name='Nom_pere',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membre',
            name='Prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membre',
            name='Profession',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membre',
            name='Telephone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stage_stagiaire',
            name='Cerficate',
            field=models.FileField(max_length=500, null=True, upload_to='PDF/Certificates_PDF', validators=[django.core.validators.FileExtensionValidator(['pdf']), myapi.models.validate_file_nimetype]),
        ),
        migrations.AlterField(
            model_name='stage_stagiaire',
            name='PDF_Agreement',
            field=models.FileField(max_length=500, upload_to='PDF/Agreements_PDF', validators=[django.core.validators.FileExtensionValidator(['pdf']), myapi.models.validate_file_nimetype]),
        ),
        migrations.AlterField(
            model_name='stage_stagiaire',
            name='PDF_Convention',
            field=models.FileField(max_length=500, upload_to='PDF/Conventions_PDF', validators=[django.core.validators.FileExtensionValidator(['pdf']), myapi.models.validate_file_nimetype]),
        ),
        migrations.AlterField(
            model_name='stage_stagiaire',
            name='PDF_Prolongement',
            field=models.FileField(max_length=500, null=True, upload_to='PDF/Prolongments_PDF', validators=[django.core.validators.FileExtensionValidator(['pdf']), myapi.models.validate_file_nimetype]),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='Presentation',
            field=models.FileField(max_length=500, upload_to='Presentations/Interns_Presentation', validators=[django.core.validators.FileExtensionValidator(['ppt', 'pptx'])]),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='Rapport',
            field=models.FileField(max_length=500, upload_to='Docs/Rapports_Docs', validators=[django.core.validators.FileExtensionValidator(['doc', 'docx'])]),
        ),
    ]
