# Generated by Django 5.0.4 on 2024-07-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_alter_membre_a_paye_alter_membre_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage_stagiaire',
            name='prolongment',
        ),
    ]
