# Generated by Django 5.0.4 on 2024-07-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_remove_stage_stagiaire_prolongment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage_stagiaire',
            old_name='Cerficate',
            new_name='PDF_Cerficate',
        ),
    ]
