# Generated by Django 5.0.4 on 2024-07-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_rename_cerficate_stage_stagiaire_pdf_cerficate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage_stagiaire',
            name='Certified',
            field=models.BooleanField(default=False),
        ),
    ]
