# Generated by Django 5.0.4 on 2024-07-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_stage_stagiaire_certified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage_stagiaire',
            old_name='PDF_Cerficate',
            new_name='PDF_Certificate',
        ),
    ]
