# Generated by Django 5.0.4 on 2024-07-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_rename_pdf_cerficate_stage_stagiaire_pdf_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaire',
            name='N_stage',
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='Presentation',
            field=models.FileField(max_length=500, upload_to='Presentations/Interns_Presentation'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='Rapport',
            field=models.FileField(max_length=500, upload_to='Docs/Rapports_Docs'),
        ),
    ]
