# Generated by Django 5.0.4 on 2024-07-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_remove_stagiaire_n_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaire',
            name='Annee',
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='N_stage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
