# Generated by Django 5.0.4 on 2024-07-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_alter_stagiaire_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='Annee_etude',
            field=models.CharField(choices=[], default=(2023, '-', 2024), max_length=20),
        ),
    ]
