# Generated by Django 5.0.4 on 2024-07-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0019_alter_stagiaire_annee_etude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='Annee_etude',
            field=models.CharField(choices=[], default=(2023, '-', 2024)),
        ),
    ]
