# Generated by Django 5.0.4 on 2024-07-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_alter_stagiaire_annee_etude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='Annee_etude',
            field=models.CharField(max_length=20),
        ),
    ]
