# Generated by Django 5.0.4 on 2024-08-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_alter_stagiaire_annee_etude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage_stagiaire',
            name='PDF_Convention',
        ),
    ]
