# Generated by Django 5.0.4 on 2024-08-04 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0022_remove_stage_stagiaire_pdf_convention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superviser',
            name='Id_Membre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.membre', unique=True),
        ),
    ]
