# Generated by Django 5.0.4 on 2024-08-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0024_remove_stagiaire_annee_remove_stagiaire_annee_etude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='Lieu_residence',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='membre',
            name='Nom_autre_association',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='membre',
            name='Recommandation',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='membre',
            name='Travail',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='membre',
            name='Autre_association',
            field=models.BooleanField(default=False),
        ),
    ]
