# Generated by Django 5.0.4 on 2024-08-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0025_membre_lieu_residence_membre_nom_autre_association_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='Lieu_residence',
        ),
    ]
