# Generated by Django 5.0.4 on 2024-08-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0026_remove_membre_lieu_residence_membre_is_superviser'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='is_superviser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='superviser',
            name='Id_Membre',
            field=models.IntegerField(null=True),
        ),
    ]
