# Generated by Django 5.0.4 on 2024-08-09 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0027_membre_is_superviser_alter_superviser_id_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superviser',
            name='Id_Membre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.membre', unique=True),
        ),
    ]
