# Generated by Django 5.0.4 on 2024-08-09 13:04

from django.db import migrations
from django.db import models
from django.db.models import Model

class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0028_alter_superviser_id_membre'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='is_sup',
            field=models.BooleanField(default=False),
        ),
    ]
