# Generated by Django 5.0.4 on 2024-08-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0029_rename_is_superviser_membre_is_sup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superviser',
            name='Id_Membre',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
