# Generated by Django 5.0.4 on 2024-08-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0030_remove_membre_is_superviser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='Recommandation',
        ),
    ]
