# Generated by Django 5.1.7 on 2025-03-29 14:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0032_remove_membre_is_sup_remove_membre_is_superviser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='Date_debut',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='Date_fin',
        ),
        migrations.AddField(
            model_name='stage',
            name='Date_register',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stage',
            name='Main_sup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_as_main_sup', to='myapi.superviser'),
        ),
        migrations.AddField(
            model_name='stage_stagiaire',
            name='Date_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stage_stagiaire',
            name='Date_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='membre',
            name='Nom_autre_association',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
