# Generated by Django 5.1.7 on 2025-03-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0033_remove_stage_date_debut_remove_stage_date_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superviser',
            name='Id_Membre',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
