# Generated by Django 5.1.7 on 2025-04-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0034_alter_superviser_id_membre'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='is_sup',
            field=models.BooleanField(default=False),
        ),
    ]
