# Generated by Django 5.1.7 on 2025-04-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0035_membre_is_sup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='super_stage',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='super_stage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_admin', True)), fields=('stage', 'superviser'), name='unique_admin_supervisor'),
        ),
    ]
