# Generated by Django 5.1.7 on 2025-04-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0036_alter_super_stage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
