# Generated by Django 5.1.7 on 2025-04-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0037_stagiaire_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaire',
            name='N_stage',
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='N_stage',
            field=models.ManyToManyField(through='myapi.stage_stagiaire', to='myapi.stage'),
        ),
    ]
